name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    needs: set-env-vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GCP_CREDENTIALS}}
        with:
          args: app deploy ../../app.yaml
